from django.urls import path
from .import views
urlpatterns=[
    path('',views.index,name='index'),
    path('admins',views.admin,name='admin'),
    path('admin_logout',views.admin_logout,name='admin_logout'),
    path('shop',views.shop,name='shop'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout'),
    path('account',views.account,name='account'),
    path('register',views.register,name='register'),
    path('send_otp',views.send_otp,name='send_otp'),
    path('user_register',views.user_register,name='user_register'),
    path('add_product',views.add_product,name='add_product'),
    path('add_category',views.add_category,name='add_category'),
    #path('single_pro', views.single_pro, name='single_pro'),
    path('single_pro/<int:id>', views.single_pro, name='single_pro'),
    path('add_cart', views.add_cart, name='add_cart'),
    path('cart', views.cart, name='cart'),
    path('del_cart', views.del_cart, name='del_cart'),
    path('coupon_check', views.coupon_check, name='coupon_check'),
    path('checkout', views.checkout, name='checkout'),
    path('single_cart', views.single_cart, name='single_cart'),
    path('rmv_cart', views.rmv_cart, name='rmv_cart'),
    path('ready_single', views.ready_single, name='ready_single'),
    path('clear_cart', views.clear_cart, name='clear_cart'),
    path('clear_wish', views.clear_wish, name='clear_wish'),
    path('ready_all', views.ready_all, name='ready_all'),
    path('wishlist', views.wishlist, name='wishlist'),
    path('wish_add', views.wish_add, name='wish_add'),
    path('del_wish', views.del_wish, name='del_wish'),
    path('search', views.search, name='search'),
    path('about', views.about, name='about'),
    path('add_address', views.add_address, name='add_address'),
    path('delete_address/<int:id>', views.delete_address, name='delete_address'),
    path('edit_address', views.edit_address, name='edit_address'),
    path('set_default/<int:id>', views.set_default, name='set_default'),
    path('ordered', views.ordered, name='ordered'),
    path('order_view', views.order_view, name='order_view'),
    path('confirm_order', views.confirm_order, name='confirm_order'),
    path('change_pass', views.change_pass, name='change_pass'),
    path('change_user', views.change_user, name='change_user'),
    path('admin_users', views.admin_users, name='admin_users'),
    path('all_products', views.all_products, name='all_products'),
    path('forgot', views.forgot, name='forgot'),
    path('forgot_otp', views.forgot_otp, name='forgot_otp'),
    path('forgot_pass', views.forgot_pass, name='forgot_pass'),
    path('delete_product', views.delete_product, name='delete_product'),


]