# Generated by Django 3.0.3 on 2020-02-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinefoods', '0012_auto_20200228_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='totals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default=0, max_length=100)),
                ('total', models.FloatField(default=0)),
                ('delivery', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0)),
            ],
        ),
    ]
