# Generated by Django 3.0.3 on 2020-02-28 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinefoods', '0013_totals'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='totals',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='total',
            old_name='total',
            new_name='subtotal',
        ),
    ]
