# Generated by Django 3.0.3 on 2020-02-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinefoods', '0014_auto_20200228_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='total',
            name='totals',
            field=models.FloatField(default=0),
        ),
    ]
