# Generated by Django 3.0.3 on 2020-02-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinefoods', '0015_total_totals'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='counts',
            field=models.IntegerField(default=0),
        ),
    ]
