# Generated by Django 3.0.3 on 2020-02-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinefoods', '0016_carts_counts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carts',
            name='counts',
        ),
        migrations.AddField(
            model_name='total',
            name='counts',
            field=models.IntegerField(default=0),
        ),
    ]
