# Generated by Django 3.0.3 on 2020-02-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinefoods', '0017_auto_20200229_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishlists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default=0, max_length=100)),
                ('wish_pid', models.IntegerField()),
                ('wish_pname', models.CharField(max_length=100)),
            ],
        ),
    ]
