# Generated by Django 3.0.3 on 2020-03-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinefoods', '0018_wishlists'),
    ]

    operations = [
        migrations.CreateModel(
            name='addresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('state', models.CharField(default='kerala', max_length=100)),
                ('district', models.CharField(default='kozhikode', max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('zip', models.IntegerField(max_length=6)),
                ('phone', models.IntegerField(max_length=10)),
            ],
        ),
    ]
