# Generated by Django 3.0.3 on 2020-03-03 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinefoods', '0019_addresses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresses',
            old_name='place',
            new_name='adname',
        ),
    ]
