# Generated by Django 3.0.3 on 2020-03-04 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinefoods', '0020_auto_20200303_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresses',
            old_name='address',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='addresses',
            old_name='adname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='addresses',
            name='district',
        ),
        migrations.AddField(
            model_name='addresses',
            name='appartment',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='addresses',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='addresses',
            name='streetaddress',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addresses',
            name='phone',
            field=models.IntegerField(max_length=12),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
