# Generated by Django 3.0.3 on 2020-03-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinefoods', '0021_auto_20200304_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='default',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
