# Generated by Django 3.0.3 on 2020-03-04 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinefoods', '0023_auto_20200304_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresses',
            old_name='default',
            new_name='defaults',
        ),
    ]
