# Generated by Django 3.0.3 on 2020-03-04 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinefoods', '0024_auto_20200304_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresses',
            name='defaults',
        ),
    ]
