# Generated by Django 3.0.3 on 2020-03-04 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinefoods', '0025_remove_addresses_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
