# Generated by Django 3.0.3 on 2020-03-04 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinefoods', '0026_auto_20200304_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='default',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
