# Generated by Django 3.0.3 on 2020-03-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinefoods', '0028_remove_addresses_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='default',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
