# Generated by Django 3.0.3 on 2020-03-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinefoods', '0029_addresses_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='user',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='total',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
