# Generated by Django 3.0.3 on 2020-03-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinefoods', '0030_auto_20200304_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('pname', models.CharField(max_length=100)),
                ('pimage', models.ImageField(null=True, upload_to='')),
                ('qty', models.IntegerField(default=1)),
                ('price', models.FloatField()),
                ('subtotal', models.FloatField(default=0)),
                ('delivery', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('totals', models.FloatField(default=0)),
                ('counts', models.IntegerField(default=0)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
