# Generated by Django 3.0.3 on 2020-03-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinefoods', '0031_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='counts',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivery',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='qty',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='subtotal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='totals',
            field=models.FloatField(),
        ),
    ]
