# Generated by Django 3.0.3 on 2020-03-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinefoods', '0032_auto_20200304_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('subtotal', models.FloatField()),
                ('delivery', models.FloatField()),
                ('discount', models.FloatField(default=0)),
                ('totals', models.FloatField()),
                ('counts', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='orders',
            name='address',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='counts',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='totals',
        ),
    ]
