# Generated by Django 3.0.3 on 2020-03-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinefoods', '0033_auto_20200304_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_total',
            old_name='totals',
            new_name='total',
        ),
        migrations.AddField(
            model_name='order_total',
            name='appartment',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order_total',
            name='city',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_total',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order_total',
            name='zip',
            field=models.IntegerField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
