# Generated by Django 3.0.3 on 2020-03-04 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinefoods', '0036_orders_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='date',
        ),
    ]
