# Generated by Django 3.0.3 on 2020-03-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinefoods', '0038_orders_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='date',
        ),
        migrations.AddField(
            model_name='order_total',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
