# Generated by Django 3.0.3 on 2020-03-05 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinefoods', '0040_auto_20200305_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_total',
            name='orderid',
        ),
    ]
