# Generated by Django 3.0.3 on 2020-03-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinefoods', '0042_order_total_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addresses',
            name='zip',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order_total',
            name='zip',
            field=models.IntegerField(),
        ),
    ]
